---
name: Test Build

on:
  workflow_dispatch:
  pull_request:

jobs:
  test_build:
    name: Test Image Build
    uses: sdr-enthusiasts/common-github-workflows/.github/workflows/sdre.yml@main
    with:
      push_enabled: false
      ghcr_repo_owner: ${{ github.repository_owner }}
      ghcr_repo: ${{ github.repository }}
      docker_build_file: Dockerfile
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}

  require_test_build_success:
    name: Require test_build success
    runs-on: ubuntu-latest
    needs: [test_build]
    if: always()
    steps:
      - name: Fail if test_build did not succeed
        run: |
          echo "test_build result: ${{ needs.test_build.result }}"

          if [ "${{ needs.test_build.result }}" != "success" ]; then
            echo "::error::test_build workflow did not fully succeed"
            exit 1
          fi
